pluginManagement {
    repositories {
        maven {
            url = "https://repo.papermc.io/repository/maven-public/"
        }
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'camera'

include ':director'
